### ISSUE TITLE
A question about Source Image Segmentation

### ISSUE THREAD

**Issue by ziyuanzhangtony** [balakg/posewarp-cvpr2018#5]
Amazing work! Thank you for sharing this!

I have a question about section 3.2. Source Image Segmentation in paper. Little bit confused. I saw state of art segmentation in paper so I only want to use this part for my project. But vggl loss is for minimizing the whole network loss end to end, there no loss for this part particularly. So how if I want this part only? Plus, does it work with dynamic/changed background e.g. person re-id problems?.

Thanks in advance

**Comment by balakg** [comment]
It's true, there's only one loss on the final image. The network learns to do segmentation in order to achieve a good loss on the final image. It's not possible to train the segmentation part on its own. You would have to train the full model, and then you can take out the segmentation module to work with your project.
